### PR TITLE
feat: add configuration option with default value for keepalive timeout to server.xml

### LINKED ISSUE #925: Potential issue gorouter  and uaa
similar to https://github.com/cloudfoundry/java-buildpack/pull/1078 , UAA should change server.xml

details
https://knowledge.broadcom.com/external/article/298104/intermittent-502-eof-gorouter-errors-for.html

### PR DESCRIPTION
**Pull request by tack-sap**
Addresses #925 

Makes the keepAliveTimeout in the server.xml configurable for both Connectors. Sets a default value of 120000 which should already resolve the problems described in the issue. Other values can be set via uaa.yml.

### CODE REVIEW

**Comment by duanemay** [comment]
With this change the -1 value is not being allowed. The value -1 is used to indicate no (i.e. infinite) timeout. Just wanted to check that this was intentional.

**Comment by peterhaochen47** [comment]
+1 with Duane's question above. Aside from that, LGTM.

Good that the default (120k milliseconds) for this new property is higher (aka longer keepalive timeout) than before this PR (which is 20k milliseconds in our case, according to the logic described in [tomcat docs](https://tomcat.apache.org/tomcat-9.0-doc/config/ajp.html)). So there shouldn't be a breaking change.

**Comment by tack-sap** [comment]
Thank you for the feedback. It was not intentional, so I added the -1 as possible value for the configuration.

**Review by peterhaochen47 — APPROVED** [review]

**Review by strehle — APPROVED** [review]
personally I would stay with default, which is 60000 instead of 120000 but OK because we can configure it.

keepAliveTimeout -> https://tomcat.apache.org/connectors-doc/common_howto/timeouts.html

**Comment by tack-sap** [comment]
> personally I would stay with default, which is 60000 instead of 120000 but OK because we can configure it.
> 
> keepAliveTimeout -> https://tomcat.apache.org/connectors-doc/common_howto/timeouts.html

As the 60000 value is causing the problems in combination with the gorouter I decided for the value that is proposed to solve the issues as default.

**Comment by strehle** [comment]
> the 60000 value is causing the problems

yes, but it seems to be a SAP problem only, because no other party as asked for it, however we will see if it causes problems for others

**Comment by ttrabold** [comment]
I don't think that it's a SAP problem only --> https://knowledge.broadcom.com/external/article/298104/intermittent-502-eof-gorouter-errors-for.html

**Pull request merged**
