### PR TITLE
Add bosh-dns healthy script to match the route_registrar health_check

### PR DESCRIPTION
**Pull request by andrew-edgar**
This change will provide the UAA specific bosh dns healthcheck.

### CODE REVIEW

**Comment by andrew-edgar** [comment]
As an aside I would like to propose that the bin/health_check be removed and both bosh_dns and route_registrar use bin/dns/healthy.  So then we are using the SAME script.  but I don't see in the UAA release how that would be enforced in the bosh deployments.  Any suggestions?  Could we work to deprecate the bin/health_check in favour of bin/dns/healthy?

**Comment by shamus** [comment]
LGTM.

I agree with you, the duplication between `bin/dns/healthy` and `bin/health_check` is meh. There are options:
1. extract a health_check function somewhere and then source that file in both `bin/dns/healthy` and `bin/health_check`
1. make a PR changing updating cf-deployment here https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L694

The first option is maybe a bit much. The second option requires this PR to merged and a release to be cut first.

Either way, I'm comfortable with the duplication in the short term. I'll merge by EOD unless there are concerns.

**Comment by andrew-edgar** [comment]
Thanks yeah I think this is right.  lets leave them duplicated.  then we can 

1) PR cf-deployment to change
2) then we remove the old script here.  

Will just take a couple of steps and done over a few releases :)

Thanks!

**Comment by dbeneke** [comment]
Released as part of UAA v74.11.0.  Thank you for the PR!

https://github.com/cloudfoundry/uaa/releases/tag/v74.11.0

**Pull request merged**
