### PR TITLE
Add Bosh Backup and Restore scripts

### PR DESCRIPTION
**Pull request by tinygrasshopper**
- We only backup if the UAA has been co-located with a postgres, like it would be for the bosh director.

cc: @kirederik

### CODE REVIEW

**Comment by fhanik** [comment]
Reverted by 13e1d0d347ee650225bb30b506870b19c042e1bc

The script only works if uaa-release is deployed with colocated postgresql. Several pipelines broke when we added this PR. It needs to be completed with

1. MySQL client packages added to uaa-releases and deployed with UAA job
2. PostgreSQL client packages added to uaa-releases and deployed with UAA job
3. Script to handle both databases
4. templates to read correct database properties

```21:37:21 | Preparing deployment: Preparing deployment (00:00:01)

21:37:27 | Error: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'uaa'. Errors are:
     - Unable to render templates for job 'uaa'. Errors are:
       - Error filling in template 'b-backup.erb' (line 19: Can't find property '["uaadb.address"]')
       - Error filling in template 'b-restore.erb' (line 19: Can't find property '["uaadb.address"]')```

**Comment by jhamon** [comment]
Just to add a little clarification for @tinygrasshopper, the UAA bosh release needs to support configuring the database location using either `p('uaadb.address')` or using a bosh-linked database resource. Right now it looks like the files changed in this PR are only handling the manifest property case, so any deployments trying to configure the uaadb using bosh links are going to be broken.

To see an example of how we accommodate multiple ways of setting database address,  check out this section of the `jobs/uaa/templates/uaa.yml.erb`: https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/uaa.yml.erb#L73

This level of complexity in our erb templates has led us to adding rspec test coverage for some of our templates.  Since the output of these BBR templates are shell files and not a ruby script, we'll probably want to add some tests similar to [these ones from Pivotal Account](https://github.com/pivotal-cf/pivotal-account-release/blob/develop/spec/errand.sh.erb_spec.rb). I'm happy to cross-team pair with somebody from BBR to get this done if needed.

CC: @sreetummidi @tnwang

**Comment by tinygrasshopper** [comment]
@jhamon thanks for the clarification, we will play a story to fix this and raise another PR

**Comment by tinygrasshopper** [comment]
@fhanik The backup and restore workflow only be supported by a co-located PostgreSQL, for now. 

We will enhance the scripts to guard against having an effect if anything other than PostgreSQL is configured. Can you please give us a link to the pipelines that failed?

**Pull request merged**
