### PR TITLE
add support for TLSv1.3

### PR DESCRIPTION
**Pull request by adam-jian-zhang**
add support for TLSv1.3 for the tomcat

### CODE REVIEW

**Comment by adam-jian-zhang** [comment]
Previous PR https://github.com/cloudfoundry/uaa-release/pull/534 behind too much. Submit the PR again.

**Comment by bruce-ricard** [comment]
The code looks good, though I have no idea if this will actually work.

Did you validate that your change is working @adam-jian-zhang ? By, for example, deploying the new uaa release and validating the TLS 1.3 is used and that both new ciphers can be used?

**Comment by adam-jian-zhang** [comment]
@bruce-ricard, I did not deploy new uaa release. 
I manually applied the configuration on /var/vcap/data/uaa/tomcat/conf/server.xml and restarted uaa job, and verified it that both TLS1.2 and TLS1.3 can be used, see below, before the change only TLS1.2 work,
```bash
kubo@jumper:~/adam$ openssl s_client  -tls1_2 -connect  88.0.0.13:8443 -CAfile root.ca
CONNECTED(00000003)
Can't use SSL_get_servername
depth=1 C = US, O = Pivotal
verify return:1
depth=0 C = US, O = Pivotal, CN = *.pks.local
verify return:1
---
Certificate chain
 0 s:C = US, O = Pivotal, CN = *.pks.local
   i:C = US, O = Pivotal
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDbjCCAlagAwIBAgIVALbM+/OzT7z28jIX3/oRYjS4wgQwMA0GCSqGSIb3DQEB
CwUAMB8xCzAJBgNVBAYTAlVTMRAwDgYDVQQKDAdQaXZvdGFsMB4XDTIzMDExNTEx
Mjc0MFoXDTI1MDExNTExMjc0MFowNTELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bp
dm90YWwxFDASBgNVBAMMCyoucGtzLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA0OcZrBKDCTbDOVxCJW4KmjFEnItcPrOY1LlL6P9sR/VLtSm9
xFsHJPxuQCSgRW/jUZxSmLeMJHJ9zYupMQd6wsNETToCq5y59k/ITP6OhTIA/apO
7KX27QKeDz7+IiTZFnENDWQvIo8/zVBdPR5iC+DicSEoEtVsMABtamSV8sjUbFbM
qnlFlEB5Nlx/gCe1IfqDtMBtHrW5qufZeR32HBmJfBHEj1MGlF5+R0X0kJRFCgHZ
rLV2AdJswXunbXKE6YJJotdZi+o8/zM4rHu1k+9BxyH29UsNi6hRuMxR9XDqcPjG
1QRWSpvnas4/G309T/fR74wU17WtjhT+VTAQHQIDAQABo4GKMIGHMB0GA1UdDgQW
BBSbdzY8V6BUQdh/zSu/X/p/widsbjAfBgNVHSMEGDAWgBTR8wrecTe7h5UAvwn7
BoB5LKJkBzAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDgYDVR0PAQH/
BAQDAgWgMBYGA1UdEQQPMA2CCyoucGtzLmxvY2FsMA0GCSqGSIb3DQEBCwUAA4IB
AQCSEgM1VLzJrcJ/85jy2Gg9Dr8FJ+M4+cPrk6iHX0uiW3l/uFwBjDmvhxV5XYyj
vhRB0v47t5HsNhRG/uotyrH1kt9pbtBnZVfmhGeVLnG5pC6qOwVlXsYmof1GB8gR
gDT/vssSxOwD9oJoKiqqtDmy85wFYqbLgxmJFXdk6cd2xpOCFNqJViZ+AEHowcQZ
OUS5lKdy1JoL0+qJ2Odtuu8RCKZgUDvSa7feTqbK7i4OcTzaplOuUZNZYH2pNKul
JEqSQMH0Jz3S+rTvhOSsKrPEXhV83uxJpflg5eYHNhfERQI3dsWlQyDPlzQ9dlUw
VcYrjHA2Tae7gGWavztaUNe0
-----END CERTIFICATE-----
subject=C = US, O = Pivotal, CN = *.pks.local

issuer=C = US, O = Pivotal

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1337 bytes and written 281 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: E50CC3536CBA5269591F8C18E961458FBDBE49CA98DF270229C05BDB440EC073
    Session-ID-ctx: 
    Master-Key: 5210931D4D2A179B2AD20B505BC113DC5B86DD473D989BDF099EBF18FB61FB8B3B761B3A28949B30A099BC0FF5EC8055
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1678931394
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
^C
kubo@jumper:~/adam$ openssl s_client  -tls1_3 -connect  88.0.0.13:8443 -CAfile root.ca
CONNECTED(00000003)
Can't use SSL_get_servername
depth=1 C = US, O = Pivotal
verify return:1
depth=0 C = US, O = Pivotal, CN = *.pks.local
verify return:1
---
Certificate chain
 0 s:C = US, O = Pivotal, CN = *.pks.local
   i:C = US, O = Pivotal
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDbjCCAlagAwIBAgIVALbM+/OzT7z28jIX3/oRYjS4wgQwMA0GCSqGSIb3DQEB
CwUAMB8xCzAJBgNVBAYTAlVTMRAwDgYDVQQKDAdQaXZvdGFsMB4XDTIzMDExNTEx
Mjc0MFoXDTI1MDExNTExMjc0MFowNTELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bp
dm90YWwxFDASBgNVBAMMCyoucGtzLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA0OcZrBKDCTbDOVxCJW4KmjFEnItcPrOY1LlL6P9sR/VLtSm9
xFsHJPxuQCSgRW/jUZxSmLeMJHJ9zYupMQd6wsNETToCq5y59k/ITP6OhTIA/apO
7KX27QKeDz7+IiTZFnENDWQvIo8/zVBdPR5iC+DicSEoEtVsMABtamSV8sjUbFbM
qnlFlEB5Nlx/gCe1IfqDtMBtHrW5qufZeR32HBmJfBHEj1MGlF5+R0X0kJRFCgHZ
rLV2AdJswXunbXKE6YJJotdZi+o8/zM4rHu1k+9BxyH29UsNi6hRuMxR9XDqcPjG
1QRWSpvnas4/G309T/fR74wU17WtjhT+VTAQHQIDAQABo4GKMIGHMB0GA1UdDgQW
BBSbdzY8V6BUQdh/zSu/X/p/widsbjAfBgNVHSMEGDAWgBTR8wrecTe7h5UAvwn7
BoB5LKJkBzAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDgYDVR0PAQH/
BAQDAgWgMBYGA1UdEQQPMA2CCyoucGtzLmxvY2FsMA0GCSqGSIb3DQEBCwUAA4IB
AQCSEgM1VLzJrcJ/85jy2Gg9Dr8FJ+M4+cPrk6iHX0uiW3l/uFwBjDmvhxV5XYyj
vhRB0v47t5HsNhRG/uotyrH1kt9pbtBnZVfmhGeVLnG5pC6qOwVlXsYmof1GB8gR
gDT/vssSxOwD9oJoKiqqtDmy85wFYqbLgxmJFXdk6cd2xpOCFNqJViZ+AEHowcQZ
OUS5lKdy1JoL0+qJ2Odtuu8RCKZgUDvSa7feTqbK7i4OcTzaplOuUZNZYH2pNKul
JEqSQMH0Jz3S+rTvhOSsKrPEXhV83uxJpflg5eYHNhfERQI3dsWlQyDPlzQ9dlUw
VcYrjHA2Tae7gGWavztaUNe0
-----END CERTIFICATE-----
subject=C = US, O = Pivotal, CN = *.pks.local

issuer=C = US, O = Pivotal

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1414 bytes and written 295 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: EFE64C3C055CA1BDB739D8C66EB648F05FA897F258FE7DA5F7F356B308E8E892
    Session-ID-ctx: 
    Resumption PSK: 0AA106C42D500DF49422B81AB8D77F08B2CE20BCEA653840CD4FE70D790C5334F1F7AE8B3506B4B9EA8E40A87C33F627
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 86400 (seconds)
    TLS session ticket:
    0000 - 8c 6f 38 6c ff e0 56 24-98 30 64 f1 14 5b 2a 52   .o8l..V$.0d..[*R
    0010 - f9 d0 d2 f2 00 82 fb 45-ac 64 49 8c 0e 7e 21 51   .......E.dI..~!Q

    Start Time: 1678931402
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
^C
```

**Comment by strehle** [comment]
@torsten-sap Can you please clarify with our Ops-Colleagues that our infrastructure will be able to use both or do we need to have it excluded ?

@bruce-ricard  I vote for a configuration as other values in this template are configurable

**Comment by bruce-ricard** [comment]
> @torsten-sap Can you please clarify with our Ops-Colleagues that our infrastructure will be able to use both or do we need to have it excluded ?

As far as I understand, this change is fully additive: it shouldn't break anyone. It only allows clients to connect using TLS 1.3, if they so desire. 

> @bruce-ricard I vote for a configuration as other values in this template are configurable

I don't think that it should be part of this PR, since as mentioned above, this change is fully additive. But I do agree that it would be a nice feature to be able to configure this. I could totally imagine a user wanting to disable TLS 1.2, and hence only configure TLS 1.3 for this field.

**Comment by YanzhaoLi** [comment]
Can we have the timeline to have this fix in the new UAA release?

**Comment by strehle** [comment]
> since as mentioned above, this change is fully additive. 

Not completely because of [TLS negotiation](https://security.stackexchange.com/questions/168390/how-is-the-tls-version-selected-between-client-and-server), so clients without 1.3 support wont see an effect but other simply switch to it (1.3) and then there could be side effects, because before we have never tested the version.

I mention it because we had this in past already with discussions about allowing only TLS 1.2  or we had WAF (web application firewall issues) so my point is , with this change we could have a different behavior and then we have to revert the UAA in our deployment because we cannot change it in YAML config.

**Comment by adam-jian-zhang** [comment]
@strehle, @bruce-ricard , I have add two properties uaa.ssl.enabled_protocols, uaa.ssl.ciphers to make it configurable, as suggested.
The default value is set to include both TLSv1.2 and TLSv1.3, and its supported ciphers, it should serve well for most users.
For those who care to pick their TLS versions, they can  customize those two properties.

**Review by strehle — APPROVED** [review]

**Pull request merged**
