### PR TITLE
Add workarounds for colocation with os-conf ca_certs job for issue #71

### PR DESCRIPTION
**Pull request by DRuggeri**
As noted in #71, here is a hacky patch for discussion.

### CODE REVIEW

**Comment by DRuggeri** [comment]
Seeking feedback

**Comment by DennisDenuto** [comment]
Eh, I've seen hackier :-) 
WDYT about moving the part of the uaa `pre-start` logic pertaining to the building of the Java keystore file if the ca-certificate has changed from `pre-start` to instead into `uaa_ctl`

`os-conf` updates ca-certs in its `pre-start` script. Bosh will run `pre-start` on each of the jobs and waits until all the `pre-start` scripts are finished. Therefore you can assume (when running in `uaa_ctl`) that if `os-conf` is co-located, it has already updated the ca certs on the vm (since it ran during the `pre-start` lifecycle)

**Comment by DRuggeri** [comment]
Thanks, @DennisDenuto! Actually, I think that's a much cleaner solution. It doesn't quite stick with the spirit of what should be done during start versus pre-start, but addresses the problem and is much less of a hack. I'll update this PR with this proposed idea instead of a sleep statement.

**Comment by DRuggeri** [comment]
Went ahead and updated PR to move the cert manipulation to the start section of uaa_ctl

**Comment by DennisDenuto** [comment]
@DRuggeri thanks for the updated PR. we have added a chore for someone on the team to review this PR.

**Comment by amuessig** [comment]
How about this pull request? I suffer from exactly the same issue as mentioned in https://github.com/cloudfoundry/uaa/issues/766

**Comment by DennisDenuto** [comment]
We have made some additional commits to address this issue.
see https://github.com/cloudfoundry/uaa-release/commit/61ae508f5344bd31322d6301379e4320540180bb

There were concerns with the `process cert` timing out the `uaa` job. Therefore if `uaa` is being deployed without `os-conf` then the certs will continue to be loaded during `pre-start`. However if `os-conf` is co-located *and* there is a race condition where os-conf loads the ca certs *after* the `uaa pre-start` job has run, then during the `start` lifecycle, every certificate will be reloaded (including the certs from the `os-conf` job)

**Pull request closed without merging**
