### PR TITLE
openjdk 8 support for ppc64le architecture

### PR DESCRIPTION
**Pull request by barthy1**
Hi,
I am part of the team, porting Cloud Foundry projects to Power microprocessor architecture.
For the uaa-release, prebuilt openjdk blobs are used. For ppc64le architecture (IBM Power 8) another openjdk 8 blob is required. My PR has all the code updates except actual blob information in blobs.yml, because it should be in the same repo as other blobs. `java-8-openjdk-ppc64le.tgz` is publicly available via http://ftp.unicamp.br/pub/ppc64el/ubuntu/14_04/cloud-foundry/java-8-openjdk-ppc64le.tgz and was packed by my team. In case if my PR in general ok with you, could you please add `8-openjdk-ppc64le.tgz` to the uaa S3 repo?

### CODE REVIEW

**Comment by fhanik** [comment]
For us to be able to handle this, we would need a repo that we can pull the latest JDK from.
In this case, `1.8.0_101` is what we are looking for. This PR contains `1.8.0_91-8u91-b14-0ubuntu4~14.04-b14`

Thank you
Filip

**Comment by fhanik** [comment]
Please also ensure that the JDK can handle unlimited key sizes, to stay compatible with the Linux and MacOS versions

**Comment by barthy1** [comment]
@fhanik We would like to be fully consistent with you approach for JDK building. Could you please point at the way, how uaa team builds the latest JDK version? I don't see this binary among currently supported binaries at https://github.com/cloudfoundry/binary-builder

**Comment by fhanik** [comment]
@barthy1 Let me get the details for you

**Comment by fhanik** [comment]
@barthy1 Yulia, found it, here are the flags that we use to build OpenJDK

https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/openjdk.sh#L22-L40

**Comment by barthy1** [comment]
@fhanik Filip, thank you for the link. 
I will check cross compile possibility for ppc64le.
Just to provide other possible solution - we are going to setup Concourse worker on OpenPower for CF buildpacks team. It can allow to run some pipeline steps directly on OpenPower (using special tag to get the right worker) and build all the binaries. Can it be also solution for your team?

**Comment by barthy1** [comment]
Build with new openjdk version - http://ftp.unicamp.br/pub/ppc64el/ubuntu/14_04/cloud-foundry/openjdk-1.8.0_101-ppc64le-trusty.tar.gz, using modified https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/openjdk-trusty.yml task for Concourse on Power.
It seems that there is no way to cross compile openjdk for ppc64le, sorry (
I am working on separate PR to support openjdk binary build for non x86 platforms using platform-specific Concourse installation.

**Comment by sreetummidi** [comment]
@fhanik Are there any steps on our side

**Pull request closed without merging**
