### PR TITLE
allow cors options to be set

### PR DESCRIPTION
**Pull request by MatthiasWinzeler**
addresses #74

### CODE REVIEW

**Comment by MatthiasWinzeler** [comment]
@sreetummidi any update on this one?

**Comment by MatthiasWinzeler** [comment]
@sreetummidi shameless bump

**Comment by MatthiasWinzeler** [comment]
trying my luck with @fhanik then - what do you think, could this be merged? :)

**Comment by rogeruiz** [comment]
We'd love for this to be incorporated into the UAA release 🙏

**Comment by fhanik** [comment]
@aramprice is your new `go-to` resource. I'm not sure how PRs are evaluated if Travis is failing.

**Comment by aramprice** [comment]
I've bumped the issue with the product team.

**Comment by MatthiasWinzeler** [comment]
@aramprice thank you very much! 

I'm actually not sure travis really fails because of the commit, since it's actually only MSSQL that's affected, and even on install time (I guess the bosh release properties do not matter at this point in time).

**Comment by pburkholder** [comment]
Hi -- Also from the cloud.gov team.  Has this feature been implemented elsewhere or are we still depending on this PR to implement.  This is going to be a compliance finding so I'm may be obliged to nudge you monthly on this (sorry).

**Comment by pburkholder** [comment]
giphy

**Comment by strehle** [comment]
@MatthiasWinzeler I know it is a long time ago, but if you want the PR, please sign the new CLA

**Comment by MatthiasWinzeler** [comment]
@strehle thanks! I signed the CLA, should be fine now.

**Comment by pburkholder** [comment]
Oh this is terrific! Thanks so much. 

giphy

**Pull request merged**
