### PR TITLE
Upgrade Java version 11 -> 17 (Bellsoft JDK 17.0.9+11)

### PR DESCRIPTION
**Pull request by peterhaochen47**

### CODE REVIEW

**Review by strehle — APPROVED** [review]
Thanks, I assume the automatic update is switched to 17 already

**Comment by Tallicia** [comment]
@strehle which automatic update are you referring to?

**Comment by strehle** [comment]
> @strehle which automatic update are you referring to?

I mean the regular job https://hush-house.pivotal.io/teams/cf-uaa/pipelines/dependencies/jobs/upgrade-java which updates the JDK for bosh release

**Comment by Tallicia** [comment]
ok, and we also have the update here included: https://github.com/pivotal/uaa-ci/blob/8ae5df9a5ffc2d99c93457e40feca4732a82dc15/concourse/dependencies/pipeline.yml#L12

**Comment by strehle** [comment]
> ok, and we also have the update here included: https://github.com/pivotal/uaa-ci/blob/8ae5df9a5ffc2d99c93457e40feca4732a82dc15/concourse/dependencies/pipeline.yml#L12

I cannot access uaa-ci but I believe you , of course :-) (but therefore I have asked)

**Comment by peterhaochen47** [comment]
Yes, the Java version autobump CI job is already updated (it will bump Java 17 patches now).

**Pull request merged**
